// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { SessionProvider } from "next-auth/react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <SessionProvider>

//         {children}
//         </SessionProvider>
//       </body>
//     </html>
//   );
// }

'use client'

import { Inter } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"
// import { SessionProvider } from "next-auth/react"

import "./globals.css"
import Providers from '@/lib/providers'

const inter = Inter({ subsets: ["latin"] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Providers>
          {children}
          <Toaster />

       </Providers>
        {/* </SessionProvider> */}
      </body>
    </html>
  )
}


